# Copyright      2022  Xiaomi Corp.       (author: Fangjun Kuang)

# See ../../LICENSE for clarification regarding multiple authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Test conda install

on:
  push:
    branches:
      - master
      - t3
  pull_request:
    types: [labeled]


jobs:
  test-conda-install:
    if: github.event.label.name == 'ready' || github.event.label.name == 'cpp' || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        torch: ["1.12.0"]
        python-version: ["3.8"]

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sherpa

      - name: Display CONDA_PREFIX
        shell: bash -l {0}
        run: |
          echo "CONDA_PREFIX: $CONDA_PREFIX"
          ls -l  $CONDA_PREFIX

      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install -c k2-fsa -c k2-fsa-sherpa -c kaldifeat -c kaldi_native_io -c pytorch k2 sherpa kaldifeat kaldi_native_io pytorch=${{ matrix.torch }} python=${{ matrix.python-version }}

      - name: Display sherpa version
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash -l {0}
        run: |
          sherpa-version

          sherpa --help

      - name: Display sherpa version
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/bin:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/lib:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/torch/lib:$PATH
          ls -lh $CONDA_PREFIX/lib/site-packages/sherpa/bin
          $CONDA_PREFIX/lib/site-packages/sherpa/bin/sherpa-version.exe 

          $CONDA_PREFIX/lib/site-packages/sherpa/bin/sherpa.exe --help


      - name: Download pretrained model and test-data
        shell: bash
        run: |
          git lfs install
          git clone https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13

      - name: Test decoding a single wave
        shell: bash -l {0}
        run: |
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/bin:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/lib:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/torch/lib:$PATH

          echo "Test greedy search"

          sherpa \
            --decoding-method=greedy_search \
            --nn-model=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/exp/cpu_jit.pt \
            --tokens=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500/tokens.txt \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1089-134686-0001.wav

          echo "Test modified_beam_search"

          sherpa \
            --decoding-method=modified_beam_search \
            --num-active-paths=4 \
            --nn-model=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/exp/cpu_jit.pt \
            --tokens=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500/tokens.txt \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1089-134686-0001.wav

      - name: Test decoding multiple waves
        shell: bash -l {0}
        run: |
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/bin:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/sherpa/lib:$PATH
          export PATH=$CONDA_PREFIX/lib/site-packages/torch/lib:$PATH

          echo "Test greedy search"

          sherpa \
            --decoding-method=greedy_search \
            --nn-model=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/exp/cpu_jit.pt \
            --tokens=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500/tokens.txt \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1089-134686-0001.wav \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0001.wav \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0002.wav

          echo "Test modified_beam_search"

          sherpa \
            --decoding-method=modified_beam_search \
            --num-active-paths=4 \
            --nn-model=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/exp/cpu_jit.pt \
            --tokens=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500/tokens.txt \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1089-134686-0001.wav \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0001.wav \
            icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0002.wav
